/*
 A Tic Tac Toe game in JAVA using swing.(2 player)
 */
package TicTacToe;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author Suman Mahanty
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    int count=1;
    int sp,p1s,p2s,bpress;
    String sp1,sp2;
    public TicTacToe() {
        super("TIC TAC TOE");
        initComponents();
        disable(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jp1 = new javax.swing.JTextField();
        jp2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        javax.swing.JTextField jby = new javax.swing.JTextField();
        result = new javax.swing.JTextField();
        p1score = new javax.swing.JTextField();
        p2score = new javax.swing.JTextField();
        p1turn = new javax.swing.JTextField();
        p2turn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Player :1");

        jp1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jp1.setForeground(new java.awt.Color(204, 51, 0));

        jp2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jp2.setForeground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Player :2");

        start.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 0));
        b1.setToolTipText("");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 0, 0));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 0, 0));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 0, 0));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 0, 0));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 0, 0));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 0, 0));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 0, 0));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 0, 0));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jby.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jby.setText("Created By: Suman Chandra Mahanty");
        jby.setEditable(false);
        jby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbyActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        result.setForeground(new java.awt.Color(0, 255, 0));
        result.setEditable(false);

        p1score.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        p1score.setText("0");
        p1score.setEditable(false);

        p2score.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        p2score.setText("0");
        p2score.setEditable(false);

        p1turn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        p1turn.setForeground(new java.awt.Color(204, 51, 0));
        p1turn.setEditable(false);

        p2turn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        p2turn.setForeground(new java.awt.Color(0, 0, 255));
        p2turn.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(start)
                                .addGap(29, 29, 29)
                                .addComponent(reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(p1score, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(p1turn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(p2score, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(jp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(p2turn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(p2score, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addComponent(p1score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1turn)
                    .addComponent(p2turn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(b8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b1);
        if(bb==false)
        {
            if(state==1)
            b1.setLabel("X");
            else if(state==0)
            {
                b1.setForeground(Color.blue);
                b1.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b2);
        if(bb==false)
        {
            if(state==1)
            b2.setLabel("X");
            else if(state==0)
            {
                b2.setForeground(Color.blue);
                b2.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b3);
        if(bb==false)
        {
            if(state==1)
            b3.setLabel("X");
            else if(state==0)
            {
                b3.setForeground(Color.blue);
                b3.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b6);
        if(bb==false)
        {
            if(state==1)
            b6.setLabel("X");
            else if(state==0)
            {
                b6.setForeground(Color.blue);
                b6.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b5);
        if(bb==false)
        {
            if(state==1)
            b5.setLabel("X");
            else if(state==0)
            {
                b5.setForeground(Color.blue);
                b5.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b4);
        if(bb==false)
        {
            if(state==1)
            b4.setLabel("X");
            else if(state==0)
            {
                b4.setForeground(Color.blue);
                b4.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b7);
        if(bb==false)
        {
            if(state==1)
            b7.setLabel("X");
            else if(state==0)
            {
                b7.setForeground(Color.blue);
                b7.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b8);
        if(bb==false)
        {
            if(state==1)
            b8.setLabel("X");
            else if(state==0)
            {
                b8.setForeground(Color.blue);
                b8.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        int state=count_State(count);
        boolean bb=button_State(b9);
        if(bb==false)
        {
            if(state==1)
            b9.setLabel("X");
            else if(state==0)
            {
                b9.setForeground(Color.blue);
                b9.setLabel("O");
            }
            bpress++;
            count++;
            check();
        }

    }//GEN-LAST:event_b9ActionPerformed

    private void jbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbyActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        sp1=jp1.getText();
        sp2=jp2.getText();
        if(sp1.equals(sp2)||sp1.equals("")||sp2.equals(""))
        {
            result.setText("Please Enter Names");
        }
        else
        {
            result.setText("");
            p1turn.setText("HIT");
            enable();
        }
    }//GEN-LAST:event_startActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        String ss1=sp1+" won";
        String ss2=sp2+" won";
        Integer i;
        if(result.getText().equals(ss1))
        {
            p1s++;
            i=p1s;
            p1score.setText(i.toString());
            jp1.setText(sp1);
        }
        else if(result.getText().equals(ss2))
        {
            p2s++;
            i=p2s;
            p2score.setText(i.toString());
            jp2.setText(sp2);
        }
        b1.setLabel("");
        b2.setLabel("");
        b3.setLabel("");
        b4.setLabel("");
        b5.setLabel("");
        b6.setLabel("");
        b7.setLabel("");
        b8.setLabel("");
        b9.setLabel("");
        b1.setForeground(Color.RED);
        b2.setForeground(Color.RED);
        b3.setForeground(Color.RED);
        b4.setForeground(Color.RED);
        b5.setForeground(Color.RED);
        b6.setForeground(Color.RED);
        b7.setForeground(Color.RED);
        b8.setForeground(Color.RED);
        b9.setForeground(Color.RED);
        p1turn.setText("");
        p2turn.setText("");
        result.setText("");
        bpress=0;
        sp=0;
        count=1;
        p1turn.setText("HIT");
        enable();
    }//GEN-LAST:event_resetActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setResizable(false);
        this.setLocation(300, 50);
    }//GEN-LAST:event_formWindowActivated

    public int count_State(int count)
    {
        if(count%2==0)
        {
            p1turn.setText("HIT");
            p2turn.setText("");
            return 0;
        }
        else
        {
            p2turn.setText("HIT");
            p1turn.setText("");
            return 1;
        }
    }
    public boolean button_State(Object ae)
    {
        JButton b=(JButton)ae;
        if(b.getLabel()=="X"||b.getLabel()=="O")
            return true;
        else
            return false;
    }
    public void check()
    {
        String s1,s2,s3,s4,s5,s6,s7,s8,s9;
        s1=b1.getLabel();
        s2=b2.getLabel();
        s3=b3.getLabel();
        s4=b4.getLabel();
        s5=b5.getLabel();
        s6=b6.getLabel();
        s7=b7.getLabel();
        s8=b8.getLabel();
        s9=b9.getLabel();
        if((s1==s2)&&(s1==s3)&&(s3!=""))
        {
            if(s1=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s1==s4)&&(s1==s7)&&(s7!=""))
        {
            if(s1=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s1==s5)&&(s1==s9)&&(s9!=""))
        {
            if(s1=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s2==s5)&&(s2==s8)&&(s8!=""))
        {
            if(s2=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s4==s5)&&(s4==s6)&&(s6!=""))
        {
            if(s4=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s3==s6)&&(s3==s9)&&(s9!=""))
        {
            if(s3=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s3==s5)&&(s3==s7)&&(s7!=""))
        {
            if(s3=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if((s7==s8)&&(s8==s9)&&(s9!=""))
        {
            if(s7=="X")
                result.setText(sp1+" won");
            else
                result.setText(sp2+" won");
            
            sp=1;
        }
        else if(bpress==9)
        {
            result.setText("DRAW");
        }
        disable(sp);
    }
    public void disable(int sp)
    {
        if(sp==1)
        {
            b1.setEnabled(false);
            b2.setEnabled(false);
            b3.setEnabled(false);
            b4.setEnabled(false);
            b5.setEnabled(false);
            b6.setEnabled(false);
            b7.setEnabled(false);
            b8.setEnabled(false);
            b9.setEnabled(false);
        }
    }
    public void enable()
    {
            b1.setEnabled(true);
            b2.setEnabled(true);
            b3.setEnabled(true);
            b4.setEnabled(true);
            b5.setEnabled(true);
            b6.setEnabled(true);
            b7.setEnabled(true);
            b8.setEnabled(true);
            b9.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jp1;
    private javax.swing.JTextField jp2;
    private javax.swing.JTextField p1score;
    private javax.swing.JTextField p1turn;
    private javax.swing.JTextField p2score;
    private javax.swing.JTextField p2turn;
    private javax.swing.JButton reset;
    private javax.swing.JTextField result;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
